### PR TITLE
Attachment features

### LINKED ISSUE #82: Ability to rename attachments
Additional menu item and dialog box prompting to enter a name

### LINKED ISSUE #87: Automatic setting of the desired flags when posting pictures
Some users suggested a feature that allows to pre-set flags when posting images, such as recalculating the hash, removing the filename, hiding metadata

### PR DESCRIPTION
**Pull request by TrixiEther**
Closes #87 

---

Added a new posting item to the media settings, which allows to select automatic flags that will be set if possible immediately when attaching a file

---

Closes #82 

---

When attaching a file, user can now select the "rename" function. When this checkbox is activated, when sending a file, it will be assigned a new name that the user enters himself or that has been configured in Preferences

Also in the settings allow to select an preconfigured name that will be assigned to all files, the "Rename" flag can also be automatically fixed for files

### CODE REVIEW

**Comment by N3-M3-S1S** [comment]
@TrixiEther I have some fixes, may i push them to this branch?

Also, there is a bug that i didn't fix:  when the original file name contains special characters, pressing "restore filename" will clear the input instead of restoring file name because the input filter does not allow special characters. Do we need that input filter?

**Comment by TrixiEther** [comment]
@N3-M3-S1S let's look at the changes to begin with, how serious they are. I know about the file name problem, but I'm not sure if it's worth solving right now. I've never seen such filenames used with a bunch of special characters. Or I myself will add it later in one of the bug fixes

**Comment by N3-M3-S1S** [comment]
@TrixiEther 
Here is the list of bugs that i found and fixed:
- When the filename is too long, it will push the extension textview out of bounds.
- When the viewport is too small (e.g. in horizontal orientation), it's impossible to reach file name edit text.

And minor code changes:
- Moved the code related to the "restore filename"  button to separate Material button view. We can use this view later if we need to add similar button somewhere else.
- Replaced listeners with existing dependency mechanism for filename related preferences.

**Comment by TrixiEther** [comment]
@N3-M3-S1S ok, let's merge that also

**Comment by N3-M3-S1S** [comment]
@TrixiEther Done.

**Comment by TrixiEther** [comment]
@N3-M3-S1S if you have created a separate button widget, it makes sense then to replace the code in the PostingFragment. This seems to have previously been the only place where a button of some sort was used... but right now it's not necessary

**Comment by N3-M3-S1S** [comment]
@TrixiEther Yeah, next time PostingFragment is modified the code for that button should be replaced with the class.

**Pull request merged**
