### PR TITLE
TrixiEther | Hide all/deleted favorite threads

### LINKED ISSUE #18: Add hiding favorites feature
If there are a lot of threads in your favorites, this can make it difficult to navigate, for example, accessing settings. It would be nice to add the ability to hide fav threads

### LINKED ISSUE #56: Add hiding deleted threads feature
It would be nice to hide at the click of a button a list of deleted threads, which often pollute favorites...
Related issue: #18

### PR DESCRIPTION
**Pull request by TrixiEther**
The feature with hiding favorites threads is ready. Added two options at once: hide the entire list of favorites, or hide only deleted threads.

Closes #18
Closes #56

### CODE REVIEW

**Comment by N3-M3-S1S** [comment]
@TrixiEther Nice. 

Later we can add some kind of indication if hidden favorite threads have new posts. For example, we can change color of the favorite button like this:

Screenshot from 2023-04-16 12-00-39

Or add a subtitle like this: 

Screenshot from 2023-04-16 12-17-41

**Review by N3-M3-S1S — COMMENTED** [review]
@TrixiEther When favorite threads are hidden, favorite boards are hidden as well. Is it intended behavior?

**Comment by TrixiEther** [comment]
@N3-M3-S1S hmm nope. This is bug :) There seems to be no type distinction in dashchan between whether a ListItem is a board or a thread. This should only apply to threads. Will have to make changes to the structure

**Comment by TrixiEther** [comment]
Fixed c8bcb74024374d06ae989e672ddd24316b713d9f

**Pull request merged**
